// Auto-generated by scripts/build-widget.mjs
// This file is the standalone Forward Widget entry for direct import.

const MEDIA_TYPES = Object.freeze({
  MOVIE: 'movie',
  TV: 'tv',
});

const SORT_KEYS = Object.freeze({
  DATE_DESC: 'date_desc',
  DATE_ASC: 'date_asc',
  RATING_DESC: 'rating_desc',
  RATING_ASC: 'rating_asc',
});

const DEFAULT_COUNT = 20;
const DEFAULT_PAGE = 1;
const MAX_COUNT = 60;
const TMDB_PAGE_SIZE = 20;

// 分类墙使用固定窗口分页。
// 稀疏分类需要放大单页绑定的远端页数，否则 Forward 端会因为当前页条目不足而停止继续翻页。
const CATALOG_SOURCE_PAGE_MULTIPLIERS = Object.freeze({
  chinese_movie: 1,
  chinese_series: 1,
  animation_movie: 1,
  animation_series: 1,
  asia_pacific_movie: 2,
  asia_pacific_series: 2,
  western_movie: 4,
  western_series: 4,
  documentary: 3,
  concert: 3,
  variety: 1,
});

const MIN_DISCOVER_VOTE_COUNT = Object.freeze({
  default: 1,
  rating: 5,
  strictForeignDate: 3,
});

const TMDB_IMAGE_BASE = 'https://image.tmdb.org/t/p';
const TMDB_LANGUAGE_SIMPLIFIED = 'zh-CN';
const TMDB_LANGUAGE_TRADITIONAL = 'zh-TW';

const STRICT_FOREIGN_CATEGORY_IDS = Object.freeze([
  'western_movie',
  'western_series',
  'asia_pacific_movie',
  'asia_pacific_series',
  'documentary',
  'concert',
]);

const CONCERT_KEYWORDS = Object.freeze([
  '演唱会',
  '演唱會',
  'Concert',
  'concert',
  'Live',
  'LIVE',
  'live',
  '巡回演唱会',
  '巡迴演唱會',
  '世界巡演',
  '巡演',
  '演奏会',
  '演奏會',
  '音乐会',
  '音樂會',
  'in concert',
  'live at',
  'live from',
  'world tour',
  'performance',
  '晚会',
  '晚會',
]);

const NORMALIZED_GROUPS = Object.freeze({
  movieChineseLanguages: Object.freeze(['zh', 'cn', 'bo', 'za', 'yue']),
  movieAsiaPacificLanguages: Object.freeze([
    'ja',
    'ko',
    'th',
    'hi',
    'ta',
    'te',
    'ml',
    'mr',
    'bn',
    'pa',
    'ur',
    'id',
    'ms',
    'vi',
    'tl',
    'fil',
  ]),
  movieWesternLanguages: Object.freeze([
    'en',
    'fr',
    'de',
    'es',
    'it',
    'nl',
    'pt',
    'ru',
    'sv',
    'no',
    'da',
    'fi',
    'pl',
    'cs',
    'hu',
    'ro',
    'el',
  ]),
  tvChineseCountries: Object.freeze(['CN', 'TW', 'HK', 'MO']),
  tvAsiaPacificCountries: Object.freeze([
    'JP',
    'KR',
    'KP',
    'TH',
    'IN',
    'SG',
    'MY',
    'PH',
    'ID',
    'VN',
    'AU',
    'NZ',
  ]),
  tvWesternCountries: Object.freeze([
    'US',
    'CA',
    'GB',
    'IE',
    'FR',
    'DE',
    'ES',
    'IT',
    'NL',
    'PT',
    'RU',
    'SE',
    'NO',
    'DK',
    'FI',
    'BE',
    'AT',
    'CH',
    'PL',
    'CZ',
    'HU',
    'RO',
    'GR',
  ]),
});

const MOVIE_RULES = Object.freeze([
  {
    id: 'concert',
    title: '演唱会',
    keywordOnly: true,
    discover: {
      genreIds: Object.freeze([10402]),
    },
    match: {
      titleKeywords: CONCERT_KEYWORDS,
    },
  },
  {
    id: 'animation_movie',
    title: '动漫电影',
    match: {
      genreIds: Object.freeze([16]),
    },
  },
  {
    id: 'documentary',
    title: '纪录片',
    match: {
      genreIds: Object.freeze([99]),
    },
  },
  {
    id: 'chinese_movie',
    title: '华语电影',
    match: {
      originalLanguages: NORMALIZED_GROUPS.movieChineseLanguages,
    },
  },
  {
    id: 'asia_pacific_movie',
    title: '亚太电影',
    match: {
      originalLanguages: NORMALIZED_GROUPS.movieAsiaPacificLanguages,
    },
  },
  {
    id: 'western_movie',
    title: '西方电影',
    catchAll: true,
    discover: {
      originalLanguages: NORMALIZED_GROUPS.movieWesternLanguages,
    },
    match: {},
  },
]);

const TV_RULES = Object.freeze([
  {
    id: 'concert',
    title: '演唱会',
    keywordOnly: true,
    match: {
      titleKeywords: CONCERT_KEYWORDS,
    },
  },
  {
    id: 'variety',
    title: '综艺',
    match: {
      genreIds: Object.freeze([10764, 10767]),
    },
  },
  {
    id: 'documentary',
    title: '纪录片',
    match: {
      genreIds: Object.freeze([99]),
    },
  },
  {
    id: 'animation_series',
    title: '动漫剧集',
    match: {
      genreIds: Object.freeze([16]),
    },
  },
  {
    id: 'chinese_series',
    title: '华语剧集',
    match: {
      originCountries: NORMALIZED_GROUPS.tvChineseCountries,
    },
  },
  {
    id: 'asia_pacific_series',
    title: '亚太剧集',
    match: {
      originCountries: NORMALIZED_GROUPS.tvAsiaPacificCountries,
    },
  },
  {
    id: 'western_series',
    title: '西方剧集',
    catchAll: true,
    discover: {
      originCountries: NORMALIZED_GROUPS.tvWesternCountries,
    },
    match: {},
  },
]);

const MEDIA_TYPE_OPTIONS = Object.freeze([
  {
    title: '电影',
    value: MEDIA_TYPES.MOVIE,
  },
  {
    title: '剧集',
    value: MEDIA_TYPES.TV,
  },
]);

const MOVIE_CATEGORY_DISPLAY_ORDER = Object.freeze([
  'chinese_movie',
  'animation_movie',
  'asia_pacific_movie',
  'western_movie',
  'documentary',
  'concert',
]);

const TV_CATEGORY_DISPLAY_ORDER = Object.freeze([
  'chinese_series',
  'animation_series',
  'asia_pacific_series',
  'western_series',
  'documentary',
  'variety',
  'concert',
]);

const CATEGORY_DISPLAY_ORDER = Object.freeze([
  'chinese_movie',
  'chinese_series',
  'animation_movie',
  'animation_series',
  'asia_pacific_movie',
  'asia_pacific_series',
  'western_movie',
  'western_series',
  'documentary',
  'variety',
  'concert',
]);

const MOVIE_CATEGORY_OPTIONS = Object.freeze(
  MOVIE_CATEGORY_DISPLAY_ORDER
    .map((ruleId) => MOVIE_RULES.find((rule) => rule.id === ruleId))
    .map((rule) => ({
      title: rule.title,
      value: rule.id,
    })),
);

const TV_CATEGORY_OPTIONS = Object.freeze(
  TV_CATEGORY_DISPLAY_ORDER
    .map((ruleId) => TV_RULES.find((rule) => rule.id === ruleId))
    .map((rule) => ({
      title: rule.title,
      value: rule.id,
    })),
);

const CATEGORY_OPTIONS = Object.freeze(
  CATEGORY_DISPLAY_ORDER.map((ruleId) => {
    const movieRule = MOVIE_RULES.find((rule) => rule.id === ruleId);
    const tvRule = TV_RULES.find((rule) => rule.id === ruleId);
    const rule = movieRule ?? tvRule;

    return {
      title: rule.title,
      value: rule.id,
    };
  }),
);

const SORT_OPTIONS = Object.freeze([
  {
    title: '日期：新到旧',
    value: SORT_KEYS.DATE_DESC,
  },
  {
    title: '日期：旧到新',
    value: SORT_KEYS.DATE_ASC,
  },
  {
    title: 'TMDb 评分：高到低',
    value: SORT_KEYS.RATING_DESC,
  },
  {
    title: 'TMDb 评分：低到高',
    value: SORT_KEYS.RATING_ASC,
  },
]);

const MOVIE_SORT_OPTIONS = SORT_OPTIONS;
const TV_SORT_OPTIONS = SORT_OPTIONS;

function getRules(mediaType) {
  return mediaType === MEDIA_TYPES.TV ? TV_RULES : MOVIE_RULES;
}

function getRuleById(mediaType, ruleId) {
  return getRules(mediaType).find((rule) => rule.id === ruleId);
}

function getCategoryOptions() {
  return CATEGORY_OPTIONS;
}

function getCategoryMediaTypes(categoryId) {
  const mediaTypes = [];

  if (getRuleById(MEDIA_TYPES.MOVIE, categoryId)) {
    mediaTypes.push(MEDIA_TYPES.MOVIE);
  }

  if (getRuleById(MEDIA_TYPES.TV, categoryId)) {
    mediaTypes.push(MEDIA_TYPES.TV);
  }

  return mediaTypes;
}

function getSortOptions() {
  return SORT_OPTIONS;
}

function getDefaultCategory() {
  return 'chinese_movie';
}

function getDefaultSort() {
  return SORT_KEYS.DATE_DESC;
}

function getCatalogSourcePageMultiplier(categoryId) {
  return CATALOG_SOURCE_PAGE_MULTIPLIERS[categoryId] ?? 1;
}

function getDefaultTmdbGet() {
  if (typeof Widget === 'undefined' || !Widget?.tmdb?.get) {
    throw new Error('当前运行环境缺少 Widget.tmdb.get，无法请求 TMDb。');
  }

  return Widget.tmdb.get.bind(Widget.tmdb);
}

function coerceInteger(value, fallback, { min = 1, max = Number.MAX_SAFE_INTEGER } = {}) {
  const parsed = Number.parseInt(String(value ?? ''), 10);

  if (!Number.isFinite(parsed)) {
    return fallback;
  }

  return Math.min(Math.max(parsed, min), max);
}

function pickValidValue(value, options, fallback) {
  const validValues = new Set(options.map((option) => option.value));
  return validValues.has(value) ? value : fallback;
}

function buildOrQuery(values) {
  return values.map((value) => String(value)).join('|');
}

function stringifyParams(rawParams = {}) {
  const result = {};

  for (const [key, value] of Object.entries(rawParams)) {
    if (value === undefined || value === null || value === '') {
      continue;
    }

    result[key] = String(value);
  }

  return result;
}

function normalizeTitle(value) {
  return typeof value === 'string' ? value.trim() : '';
}

function isMeaningfulText(value) {
  return normalizeTitle(value).length > 0;
}

function containsHan(value) {
  return /[\p{Script=Han}]/u.test(value);
}

function isUsableTmdbChineseText(value) {
  const normalizedValue = normalizeTitle(value);
  return Boolean(normalizedValue && containsHan(normalizedValue));
}

function isUsableTmdbChineseTitle(value) {
  const normalizedValue = normalizeTitle(value);
  return Boolean(normalizedValue && containsHan(normalizedValue));
}

function resolveLocalizedText({ simplifiedText, traditionalText, originalText }) {
  const simplified = normalizeTitle(simplifiedText);
  const traditional = normalizeTitle(traditionalText);
  const original = normalizeTitle(originalText);

  if (isUsableTmdbChineseText(simplified)) {
    return simplified;
  }

  if (isUsableTmdbChineseText(traditional)) {
    return traditional;
  }

  return simplified || traditional || original;
}

function resolveDisplayTitle({ simplifiedTitle, traditionalTitle, originalTitle }) {
  return resolveLocalizedText({
    simplifiedText: simplifiedTitle,
    traditionalText: traditionalTitle,
    originalText: originalTitle,
  });
}

const CACHE_VERSION = 7;
const CACHE_KEY_PREFIX = 'tmdb-category-browser:v7';
const LEGACY_CACHE_KEY_PREFIXES = Object.freeze([
  'tmdb-category-browser:v6',
  'tmdb-category-browser:v5',
  'tmdb-category-browser:v4',
]);
const CACHE_MAX_RECORDS = 1000;
const TMDB_REQUEST_TIMEOUT_MS = 8000;
const CACHE_IO_TIMEOUT_MS = 300;
const CACHE_REFRESH_TIMEOUT_MS = 1500;
const FIRST_PAGE_STALE_MAX_AGE_DAYS = 45;
const INCREMENTAL_REFRESH_MAX_SOURCE_PAGES = 3;
const INCREMENTAL_REFRESH_MAX_DAYS = 7;
const BACKFILL_INTERVAL_DAYS = 7;
const BACKFILL_LOOKBACK_DAYS = 90;
const BACKGROUND_PREFETCH_PAGES = 0;
const SOURCE_PAGE_BATCH_SIZE = 4;
const EXTRA_SOURCE_PAGE_LIMIT = 8;

function buildImageUrl(size, path) {
  return isMeaningfulText(path) ? `${TMDB_IMAGE_BASE}/${size}${path}` : '';
}

function normalizeTmdbImageUrl(size, path) {
  const normalizedPath = normalizeTitle(path);
  if (!normalizedPath) {
    return '';
  }

  if (/^https?:\/\//i.test(normalizedPath)) {
    return normalizedPath;
  }

  return normalizedPath.startsWith('/') ? buildImageUrl(size, normalizedPath) : normalizedPath;
}

function getRawTitle(item, mediaType) {
  return mediaType === MEDIA_TYPES.MOVIE ? item?.title : item?.name;
}

function getRawOriginalTitle(item, mediaType) {
  return mediaType === MEDIA_TYPES.MOVIE ? item?.original_title : item?.original_name;
}

function getRawDate(item, mediaType) {
  return mediaType === MEDIA_TYPES.MOVIE ? item?.release_date : item?.first_air_date;
}

function collectLocalizedEntries(simplifiedItems = [], traditionalItems = [], keySelector = (item) => item.id) {
  const mergedByKey = new Map();

  for (const item of traditionalItems ?? []) {
    mergedByKey.set(keySelector(item), { traditional: item });
  }

  for (const item of simplifiedItems ?? []) {
    const key = keySelector(item);
    const existing = mergedByKey.get(key) ?? {};
    existing.simplified = item;
    mergedByKey.set(key, existing);
  }

  const orderedKeys = [
    ...(simplifiedItems ?? []).map((item) => keySelector(item)),
    ...(traditionalItems ?? []).map((item) => keySelector(item)),
  ];

  return Array.from(new Set(orderedKeys))
    .map((key) => ({
      key,
      simplified: mergedByKey.get(key)?.simplified,
      traditional: mergedByKey.get(key)?.traditional,
    }))
    .filter((entry) => entry.simplified || entry.traditional);
}

function buildLocalizedRecord({
  tmdbId,
  mediaType,
  simplifiedItem,
  traditionalItem,
  titleSelector,
  originalTitleSelector = titleSelector,
  overviewSelector = (item) => item?.overview,
  dateSelector = (item) => getRawDate(item, mediaType),
  genreIdsSelector = (item) => {
    if (Array.isArray(item?.genre_ids)) {
      return item.genre_ids;
    }

    if (Array.isArray(item?.genres)) {
      return item.genres.map((genre) => genre.id).filter(Number.isFinite);
    }

    return [];
  },
  originalLanguageSelector = (item) => item?.original_language ?? '',
  originCountrySelector = (item) => (Array.isArray(item?.origin_country) ? item.origin_country : []),
  adultSelector = (item) => item?.adult === true,
  voteCountSelector = (item) => (Number.isFinite(item?.vote_count) ? item.vote_count : 0),
  voteAverageSelector = (item) => (Number.isFinite(item?.vote_average) ? item.vote_average : NaN),
  posterPathSelector = (item) => item?.poster_path,
  backdropPathSelector = (item) => item?.backdrop_path,
}) {
  const baseItem = simplifiedItem ?? traditionalItem;

  if (!baseItem) {
    return null;
  }

  const simplifiedTitle = normalizeTitle(simplifiedItem ? titleSelector(simplifiedItem) : '');
  const traditionalTitle = normalizeTitle(traditionalItem ? titleSelector(traditionalItem) : '');
  const originalTitle = normalizeTitle(originalTitleSelector(baseItem));
  const simplifiedOverview = normalizeTitle(simplifiedItem ? overviewSelector(simplifiedItem) : '');
  const traditionalOverview = normalizeTitle(traditionalItem ? overviewSelector(traditionalItem) : '');
  const originalOverview = normalizeTitle(overviewSelector(baseItem));

  return {
    tmdbId,
    mediaType,
    displayTitle: resolveDisplayTitle({
      simplifiedTitle,
      traditionalTitle,
      originalTitle,
    }),
    simplifiedTitle,
    traditionalTitle,
    originalTitle,
    overview: resolveLocalizedText({
      simplifiedText: simplifiedOverview,
      traditionalText: traditionalOverview,
      originalText: originalOverview,
    }),
    simplifiedOverview,
    traditionalOverview,
    originalOverview,
    genreIds: genreIdsSelector(baseItem),
    originalLanguage: normalizeTitle(originalLanguageSelector(baseItem)).toLowerCase(),
    originCountry: originCountrySelector(baseItem)
      .map((value) => normalizeTitle(value).toUpperCase())
      .filter(Boolean),
    releaseDate: normalizeTitle(dateSelector(baseItem)),
    adult: adultSelector(baseItem),
    voteCount: voteCountSelector(baseItem),
    voteAverage: voteAverageSelector(baseItem),
    posterPath: buildImageUrl('w500', posterPathSelector(baseItem)),
    backdropPath: buildImageUrl('w780', backdropPathSelector(baseItem)),
  };
}

function resolveCatalogDisplayTitle(record) {
  const simplifiedTitle = normalizeTitle(record?.simplifiedTitle);
  if (isUsableTmdbChineseTitle(simplifiedTitle)) {
    return simplifiedTitle;
  }

  const traditionalTitle = normalizeTitle(record?.traditionalTitle);
  if (isUsableTmdbChineseTitle(traditionalTitle)) {
    return traditionalTitle;
  }

  return '';
}

function hasLocalizedChineseCatalogTitle(record) {
  return Boolean(resolveCatalogDisplayTitle(record));
}

function getKeywordCandidates(record) {
  return Array.from(
    new Set(
      [
        record.displayTitle,
        record.simplifiedTitle,
        record.traditionalTitle,
        record.originalTitle,
        record.overview,
      ]
        .map((value) => normalizeTitle(value))
        .filter(Boolean),
    ),
  );
}

function escapeRegExp(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function matchesKeyword(candidates, keyword) {
  if (/[A-Za-z]/.test(keyword)) {
    const regex = new RegExp(`\\b${escapeRegExp(keyword)}\\b`, 'i');
    return candidates.some((candidate) => regex.test(candidate));
  }

  return candidates.some((candidate) => candidate.includes(keyword));
}

function matchesRule(record, rule) {
  const match = rule.match ?? {};

  if (match.genreIds?.length) {
    const hasGenre = record.genreIds.some((genreId) => match.genreIds.includes(genreId));
    if (!hasGenre) {
      return false;
    }
  }

  if (match.originalLanguages?.length && !match.originalLanguages.includes(record.originalLanguage)) {
    return false;
  }

  if (match.originCountries?.length) {
    const hasCountry = record.originCountry.some((countryCode) => match.originCountries.includes(countryCode));
    if (!hasCountry) {
      return false;
    }
  }

  if (match.titleKeywords?.length) {
    const candidates = getKeywordCandidates(record);
    const hasKeyword = match.titleKeywords.some((keyword) => matchesKeyword(candidates, keyword));
    if (!hasKeyword) {
      return false;
    }
  }

  return true;
}

function classifyMediaRecord(mediaType, record) {
  const rules = getRules(mediaType);

  for (const rule of rules) {
    if (rule.catchAll || matchesRule(record, rule)) {
      return rule;
    }
  }

  return null;
}

function buildRuleDiscoverParams(rule) {
  const discover = rule.discover ?? (rule.catchAll || rule.keywordOnly ? {} : rule.match);
  const params = {};

  if (discover.genreIds?.length) {
    params.with_genres = buildOrQuery(discover.genreIds);
  }

  if (discover.originalLanguages?.length) {
    params.with_original_language = buildOrQuery(discover.originalLanguages);
  }

  if (discover.originCountries?.length) {
    params.with_origin_country = buildOrQuery(discover.originCountries);
  }

  return params;
}

const GLOBAL_GENRE_MAP = Object.freeze({
  12: '冒险',
  14: '奇幻',
  16: '动画',
  18: '剧情',
  27: '恐怖',
  28: '动作',
  35: '喜剧',
  36: '历史',
  37: '西部',
  53: '惊悚',
  80: '犯罪',
  99: '纪录片',
  878: '科幻',
  9648: '悬疑',
  10402: '音乐',
  10749: '爱情',
  10751: '家庭',
  10752: '战争',
  10759: '动作冒险',
  10762: '儿童',
  10764: '真人秀',
  10765: '科幻奇幻',
  10767: '脱口秀',
});

function buildGenreText(genreIds, mediaType) {
  if (!Array.isArray(genreIds) || genreIds.length === 0) {
    return mediaType === MEDIA_TYPES.TV ? '剧集' : '电影';
  }

  const genres = genreIds
    .map((genreId) => GLOBAL_GENRE_MAP[genreId])
    .filter(Boolean)
    .slice(0, 2);

  if (!genres.length) {
    return mediaType === MEDIA_TYPES.TV ? '剧集' : '电影';
  }

  return genres.join(' / ');
}

function getMinimumVoteCount(categoryId, sortKey) {
  if (sortKey === SORT_KEYS.RATING_ASC || sortKey === SORT_KEYS.RATING_DESC) {
    return MIN_DISCOVER_VOTE_COUNT.rating;
  }

  if (STRICT_FOREIGN_CATEGORY_IDS.includes(categoryId)) {
    return MIN_DISCOVER_VOTE_COUNT.strictForeignDate;
  }

  return MIN_DISCOVER_VOTE_COUNT.default;
}

function getTmdbSortBy(mediaType, sortKey) {
  if (mediaType === MEDIA_TYPES.MOVIE) {
    switch (sortKey) {
      case SORT_KEYS.DATE_ASC:
        return 'primary_release_date.asc';
      case SORT_KEYS.DATE_DESC:
        return 'primary_release_date.desc';
      case SORT_KEYS.RATING_ASC:
        return 'vote_average.asc';
      case SORT_KEYS.RATING_DESC:
        return 'vote_average.desc';
      default:
        return 'primary_release_date.desc';
    }
  }

  switch (sortKey) {
    case SORT_KEYS.DATE_ASC:
      return 'first_air_date.asc';
    case SORT_KEYS.DATE_DESC:
      return 'first_air_date.desc';
    case SORT_KEYS.RATING_ASC:
      return 'vote_average.asc';
    case SORT_KEYS.RATING_DESC:
      return 'vote_average.desc';
    default:
      return 'first_air_date.desc';
  }
}

function getTodayDateString() {
  const now = new Date();
  const year = String(now.getFullYear());
  const month = String(now.getMonth() + 1).padStart(2, '0');
  const day = String(now.getDate()).padStart(2, '0');
  return `${year}-${month}-${day}`;
}

function buildDiscoverParams(mediaType, categoryId, rule, sortKey, sourcePage, todayDate) {
  const params = {
    include_adult: false,
    page: sourcePage,
    sort_by: getTmdbSortBy(mediaType, sortKey),
    'vote_count.gte': getMinimumVoteCount(categoryId, sortKey),
    'vote_average.gte': 0.1,
    ...buildRuleDiscoverParams(rule),
  };

  if (mediaType === MEDIA_TYPES.MOVIE) {
    params.include_video = false;
    params['primary_release_date.lte'] = todayDate;
  } else {
    params['first_air_date.lte'] = todayDate;
  }

  return stringifyParams(params);
}

function applyDiscoverDateRange(params, mediaType, dateRange) {
  if (!dateRange) {
    return params;
  }

  const fromKey = mediaType === MEDIA_TYPES.MOVIE ? 'primary_release_date.gte' : 'first_air_date.gte';
  const toKey = mediaType === MEDIA_TYPES.MOVIE ? 'primary_release_date.lte' : 'first_air_date.lte';

  return stringifyParams({
    ...params,
    [fromKey]: dateRange.from,
    [toKey]: dateRange.to,
  });
}

function mergeLocalizedResults(mediaType, simplifiedResponse, traditionalResponse) {
  const records = collectLocalizedEntries(
    simplifiedResponse?.results ?? [],
    traditionalResponse?.results ?? [],
    (item) => item.id,
  )
    .map(({ key, simplified, traditional }) =>
      buildLocalizedRecord({
        tmdbId: key,
        mediaType,
        simplifiedItem: simplified,
        traditionalItem: traditional,
        titleSelector: (item) => getRawTitle(item, mediaType),
        originalTitleSelector: (item) => getRawOriginalTitle(item, mediaType),
      }))
    .filter(Boolean);

  return {
    results: records,
    totalPages: Math.max(simplifiedResponse?.total_pages ?? 0, traditionalResponse?.total_pages ?? 0),
  };
}

async function fetchLocalizedDiscoverPage({
  mediaType,
  categoryId,
  rule,
  sortKey,
  sourcePage,
  tmdbGet,
  todayDate,
  dateRange,
}) {
  const endpoint = mediaType === MEDIA_TYPES.MOVIE ? 'discover/movie' : 'discover/tv';
  const commonParams = applyDiscoverDateRange(
    buildDiscoverParams(mediaType, categoryId, rule, sortKey, sourcePage, todayDate),
    mediaType,
    dateRange,
  );

  const [simplifiedResult, traditionalResult] = await Promise.allSettled([
    tmdbGet(endpoint, {
      params: {
        ...commonParams,
        language: TMDB_LANGUAGE_SIMPLIFIED,
      },
    }),
    tmdbGet(endpoint, {
      params: {
        ...commonParams,
        language: TMDB_LANGUAGE_TRADITIONAL,
      },
    }),
  ]);

  const simplifiedResponse = simplifiedResult.status === 'fulfilled' ? simplifiedResult.value : null;
  const traditionalResponse = traditionalResult.status === 'fulfilled' ? traditionalResult.value : null;

  if (!simplifiedResponse && !traditionalResponse) {
    // 单个远端窗口页失败不应立刻拖垮已有缓存场景；错误会上抛到窗口汇总层，
    // 冷启动且所有窗口都失败时再转成可见错误，避免把鉴权/限流误报成“无数据”。
    return {
      results: [],
      totalPages: 0,
      failed: true,
      errors: [
        {
          endpoint,
          language: TMDB_LANGUAGE_SIMPLIFIED,
          page: sourcePage,
          reason: simplifiedResult.reason instanceof Error ? simplifiedResult.reason.message : String(simplifiedResult.reason),
        },
        {
          endpoint,
          language: TMDB_LANGUAGE_TRADITIONAL,
          page: sourcePage,
          reason: traditionalResult.reason instanceof Error ? traditionalResult.reason.message : String(traditionalResult.reason),
        },
      ],
    };
  }

  return {
    ...mergeLocalizedResults(mediaType, simplifiedResponse, traditionalResponse),
    failed: false,
    errors: [],
  };
}

const EXPLICIT_ADULT_PATTERNS = [
  /\b(?:porn|pornographic|hardcore|xxx)\b/i,
  /(?:成人影片|成人视频|成人電影|黃色電影|黄片|黃片|无码|無碼|AV片|成人向)/i,
];

function containsExplicitAdultText(record) {
  const searchableText = [
    record.displayTitle,
    record.simplifiedTitle,
    record.traditionalTitle,
    record.originalTitle,
    record.overview,
  ]
    .map((value) => normalizeTitle(value))
    .filter(Boolean)
    .join('\n');

  return EXPLICIT_ADULT_PATTERNS.some((pattern) => pattern.test(searchableText));
}

function isRecordReleased(record, todayDate) {
  if (!isMeaningfulText(record.releaseDate)) {
    return true;
  }

  return record.releaseDate <= todayDate;
}

function isAllowedRecord(record, todayDate, categoryId, sortKey) {
  if (!isRecordReleased(record, todayDate)) {
    return false;
  }

  if (!Number.isFinite(record.voteAverage) || record.voteAverage <= 0) {
    return false;
  }

  if (!Number.isFinite(record.voteCount) || record.voteCount < getMinimumVoteCount(categoryId, sortKey)) {
    return false;
  }

  if (record.adult === true) {
    return false;
  }

  if (containsExplicitAdultText(record)) {
    return false;
  }

  return true;
}

function getRemotePaginationPlan(params) {
  const baseRequestedSourcePages = Math.max(1, Math.ceil(params.count / TMDB_PAGE_SIZE));
  const requestedSourcePages = baseRequestedSourcePages * getCatalogSourcePageMultiplier(params.categoryId);
  const sourceStartPage = ((params.page - 1) * requestedSourcePages) + 1;

  return {
    sourceStartPage,
    requestedSourcePages,
  };
}

function buildSelectedScopes(categoryId, sourceMediaTypes, startPage, requestedSourcePages) {
  return sourceMediaTypes
    .map((mediaType) => ({
      mediaType,
      rule: getRuleById(mediaType, categoryId),
      startPage,
      requestedSourcePages,
    }))
    .filter((scope) => scope.rule);
}

async function collectCatalogRecordsForScope({
  params,
  scope,
  tmdbGet,
  todayDate,
  sortKey = params.sortKey,
  dateRange,
}) {
  const collected = [];
  const errors = [];
  let attemptedPages = 0;
  let failedPages = 0;
  let knownTotalPages = null;
  const sourcePageLimit = dateRange
    ? scope.requestedSourcePages
    : scope.requestedSourcePages + Math.min(scope.requestedSourcePages, EXTRA_SOURCE_PAGE_LIMIT);

  // 当前 Forward 页从固定远端窗口起步，不回扫历史页；如果过滤后太稀疏，
  // 只允许向后做小幅顺延补抓，防止页面直接空掉导致 Forward 误判没有下一页。
  // 同一窗口内按小批量并发抓取，避免一页一页串行等待导致冷启动过慢。
  for (let offset = 0; offset < sourcePageLimit;) {
    if (offset >= scope.requestedSourcePages && collected.length >= params.count) {
      break;
    }

    const sourcePages = [];

    for (
      let batchOffset = 0;
      batchOffset < SOURCE_PAGE_BATCH_SIZE && offset < sourcePageLimit;
      batchOffset += 1, offset += 1
    ) {
      if (offset >= scope.requestedSourcePages && collected.length >= params.count) {
        break;
      }

      const sourcePage = scope.startPage + offset;
      if (Number.isFinite(knownTotalPages) && sourcePage > knownTotalPages) {
        break;
      }

      sourcePages.push(sourcePage);
    }

    if (!sourcePages.length) {
      break;
    }

    const localizedPages = await Promise.all(
      sourcePages.map((sourcePage) =>
        fetchLocalizedDiscoverPage({
          mediaType: scope.mediaType,
          categoryId: params.categoryId,
          rule: scope.rule,
          sortKey,
          sourcePage,
          tmdbGet,
          todayDate,
          dateRange,
        })),
    );

    for (const localizedPage of localizedPages) {
      attemptedPages += 1;
      if (localizedPage.failed) {
        failedPages += 1;
        errors.push(...(localizedPage.errors ?? []));
      }

      if (localizedPage.totalPages > 0) {
        knownTotalPages = localizedPage.totalPages;
      }

      for (const record of localizedPage.results) {
        // 过滤顺序固定：先看简/繁中文标题是否存在，再做业务过滤，最后才做分类命中判断。
        const displayTitle = resolveCatalogDisplayTitle(record);
        if (!displayTitle) {
          continue;
        }

        if (!isAllowedRecord(record, todayDate, params.categoryId, sortKey)) {
          continue;
        }

        const matchedRule = classifyMediaRecord(scope.mediaType, record);
        if (!matchedRule || matchedRule.id !== scope.rule.id) {
          continue;
        }

        record.displayTitle = displayTitle;
        collected.push(record);
      }
    }
  }

  return {
    records: collected,
    attemptedPages,
    failedPages,
    errors,
  };
}

async function collectCatalogRecords({ params, tmdbGet, todayDate, fetchPlan, sortKey, dateRange }) {
  const sourceMediaTypes = getCategoryMediaTypes(params.categoryId);
  const selectedScopes = buildSelectedScopes(
    params.categoryId,
    sourceMediaTypes,
    fetchPlan.sourceStartPage,
    fetchPlan.requestedSourcePages,
  );

  if (!selectedScopes.length) {
    throw new Error(`未知分类：${params.categoryId}`);
  }

  const scopeResults = await Promise.all(
    selectedScopes.map((scope) =>
      collectCatalogRecordsForScope({
        params,
        scope,
        tmdbGet,
        todayDate,
        sortKey,
        dateRange,
      })),
  );

  return {
    records: dedupeCatalogRecords(scopeResults.flatMap((result) => result.records)),
    categoryTitle: selectedScopes[0].rule.title,
    attemptedPages: scopeResults.reduce((sum, result) => sum + result.attemptedPages, 0),
    failedPages: scopeResults.reduce((sum, result) => sum + result.failedPages, 0),
    errors: scopeResults.flatMap((result) => result.errors),
  };
}

function dedupeCatalogRecords(records) {
  const deduped = [];
  const seenRecordKeys = new Set();

  for (const record of records) {
    const recordKey = `${record.mediaType}:${record.tmdbId}`;
    if (seenRecordKeys.has(recordKey)) {
      continue;
    }

    seenRecordKeys.add(recordKey);
    deduped.push(record);
  }

  return deduped;
}

function compareText(left, right) {
  return left.localeCompare(right, 'zh-Hans-CN', {
    numeric: true,
    sensitivity: 'base',
  });
}

function compareOptionalDate(left, right) {
  const leftDate = Date.parse(left || '');
  const rightDate = Date.parse(right || '');

  if (Number.isNaN(leftDate) && Number.isNaN(rightDate)) {
    return 0;
  }

  if (Number.isNaN(leftDate)) {
    return 1;
  }

  if (Number.isNaN(rightDate)) {
    return -1;
  }

  return leftDate - rightDate;
}

function compareOptionalNumber(left, right) {
  const safeLeft = Number.isFinite(left) ? left : -Infinity;
  const safeRight = Number.isFinite(right) ? right : -Infinity;

  if (safeLeft === safeRight) {
    return 0;
  }

  return safeLeft - safeRight;
}

function sortCatalogRecords(records, sortKey) {
  const sorted = [...records];

  sorted.sort((left, right) => {
    switch (sortKey) {
      case SORT_KEYS.DATE_ASC:
        return (
          compareOptionalDate(left.releaseDate, right.releaseDate) ||
          compareText(left.displayTitle, right.displayTitle) ||
          left.tmdbId - right.tmdbId
        );
      case SORT_KEYS.DATE_DESC:
        return (
          compareOptionalDate(right.releaseDate, left.releaseDate) ||
          compareText(left.displayTitle, right.displayTitle) ||
          left.tmdbId - right.tmdbId
        );
      case SORT_KEYS.RATING_ASC:
        return (
          compareOptionalNumber(left.voteAverage, right.voteAverage) ||
          compareOptionalDate(right.releaseDate, left.releaseDate) ||
          compareText(left.displayTitle, right.displayTitle) ||
          left.tmdbId - right.tmdbId
        );
      case SORT_KEYS.RATING_DESC:
        return (
          compareOptionalNumber(right.voteAverage, left.voteAverage) ||
          compareOptionalDate(right.releaseDate, left.releaseDate) ||
          compareText(left.displayTitle, right.displayTitle) ||
          left.tmdbId - right.tmdbId
        );
      default:
        return (
          compareOptionalDate(right.releaseDate, left.releaseDate) ||
          compareText(left.displayTitle, right.displayTitle) ||
          left.tmdbId - right.tmdbId
        );
    }
  });

  return sorted;
}

function buildDescription(record, categoryTitle) {
  const header = [record.releaseDate, categoryTitle].filter(Boolean).join(' · ');
  const overview = normalizeTitle(record.overview) || '暂无简介';

  return [header, overview].filter(Boolean).join('\n') || undefined;
}

function mapRecordToVideoItem(record, categoryTitle) {
  const tmdbId = String(record.tmdbId);

  return {
    // Forward App 实际原生 TMDb 详情查询使用纯数字 id + 数字 tmdbId + mediaType。
    // link 会让宿主有机会走 URL/custom detail 链路，反而绕开原生 TMDb 查询。
    id: tmdbId,
    tmdbId: Number(record.tmdbId),
    type: 'tmdb',
    title: record.displayTitle || record.originalTitle || `${record.mediaType}-${record.tmdbId}`,
    subTitle: '',
    posterPath: record.posterPath,
    backdropPath: record.backdropPath,
    releaseDate: record.releaseDate || undefined,
    mediaType: record.mediaType,
    genreTitle: buildGenreText(record.genreIds, record.mediaType),
    description: buildDescription(record, categoryTitle),
    rating: Number.isFinite(record.voteAverage) ? record.voteAverage : 0,
  };
}

function getCatalogCacheKey(categoryId, keyPrefix = CACHE_KEY_PREFIX) {
  return `${keyPrefix}:${categoryId}`;
}

function getDefaultStorage() {
  if (typeof Widget === 'undefined' || !Widget?.storage) {
    return null;
  }

  return Widget.storage;
}

function createEmptyCache(categoryId, todayDate) {
  return {
    version: CACHE_VERSION,
    categoryId,
    lastSyncDate: todayDate,
    lastBackfillDate: '',
    pages: {},
    records: [],
  };
}

function normalizeTmdbIdentity(record) {
  if (!record || typeof record !== 'object') {
    return null;
  }

  const explicitMediaType = record.mediaType === MEDIA_TYPES.MOVIE || record.mediaType === MEDIA_TYPES.TV
    ? record.mediaType
    : '';
  const candidates = [record.tmdbId, record.id];
  let parsedMediaType = '';
  let parsedTmdbId = NaN;

  for (const value of candidates) {
    if (Number.isFinite(value)) {
      parsedTmdbId = value;
      break;
    }

    const text = normalizeTitle(value);
    const prefixedMatch = /^(movie|tv)\.(\d+)$/i.exec(text);
    if (prefixedMatch) {
      parsedMediaType = prefixedMatch[1].toLowerCase();
      parsedTmdbId = Number.parseInt(prefixedMatch[2], 10);
      break;
    }

    if (/^\d+$/.test(text)) {
      parsedTmdbId = Number.parseInt(text, 10);
      break;
    }
  }

  const mediaType = explicitMediaType || parsedMediaType;
  if (!Number.isFinite(parsedTmdbId) || parsedTmdbId <= 0 || !mediaType) {
    return null;
  }

  return {
    tmdbId: parsedTmdbId,
    mediaType,
  };
}

function normalizeNumber(value, fallback = 0) {
  const numericValue = Number(value);
  return Number.isFinite(numericValue) ? numericValue : fallback;
}

function normalizeStringArray(value) {
  return Array.isArray(value)
    ? value.map((item) => normalizeTitle(item)).filter(Boolean)
    : [];
}

function normalizeNumberArray(value) {
  return Array.isArray(value)
    ? value.map((item) => Number(item)).filter(Number.isFinite)
    : [];
}

function hasRenderablePoster(record) {
  return isMeaningfulText(record?.posterPath);
}

function normalizeCacheRecord(record) {
  const identity = normalizeTmdbIdentity(record);
  if (!identity) {
    return null;
  }

  const normalizedRecord = {
    ...record,
    tmdbId: identity.tmdbId,
    mediaType: identity.mediaType,
    displayTitle: normalizeTitle(record.displayTitle || record.title || record.name),
    simplifiedTitle: normalizeTitle(record.simplifiedTitle),
    traditionalTitle: normalizeTitle(record.traditionalTitle),
    originalTitle: normalizeTitle(record.originalTitle),
    overview: normalizeTitle(record.overview || record.description),
    genreIds: normalizeNumberArray(record.genreIds),
    originalLanguage: normalizeTitle(record.originalLanguage).toLowerCase(),
    originCountry: normalizeStringArray(record.originCountry).map((value) => value.toUpperCase()),
    releaseDate: normalizeTitle(record.releaseDate),
    adult: record.adult === true,
    voteCount: normalizeNumber(record.voteCount),
    voteAverage: normalizeNumber(record.voteAverage),
    posterPath: normalizeTmdbImageUrl('w500', record.posterPath || record.poster_path),
    backdropPath: normalizeTmdbImageUrl('w780', record.backdropPath || record.backdrop_path),
  };

  return isValidCacheRecord(normalizedRecord) ? normalizedRecord : null;
}

function normalizeCacheRecords(records) {
  if (!Array.isArray(records)) {
    return [];
  }

  return records
    .map((record) => normalizeCacheRecord(record))
    .filter(Boolean);
}

function isValidCacheRecord(record) {
  return (
    record &&
    Number.isFinite(record.tmdbId) &&
    (record.mediaType === MEDIA_TYPES.MOVIE || record.mediaType === MEDIA_TYPES.TV) &&
    isMeaningfulText(record.displayTitle) &&
    hasRenderablePoster(record)
  );
}

function normalizeCache(rawCache, categoryId, { allowLegacy = false } = {}) {
  if (
    !rawCache ||
    (!allowLegacy && rawCache.version !== CACHE_VERSION) ||
    (rawCache.categoryId && rawCache.categoryId !== categoryId)
  ) {
    return null;
  }

  const pages = normalizeCachedPages(rawCache.pages);
  const pageRecords = Object.values(pages)
    .flatMap((pagesByNumber) => Object.values(pagesByNumber))
    .flat();

  return {
    version: CACHE_VERSION,
    categoryId,
    lastSyncDate: normalizeTitle(rawCache.lastSyncDate),
    lastBackfillDate: normalizeTitle(rawCache.lastBackfillDate),
    pages,
    records: mergeCachedRecords(normalizeCacheRecords(rawCache.records), pageRecords),
  };
}

function normalizeCachedPages(rawPages) {
  const pages = {};

  if (!rawPages || typeof rawPages !== 'object') {
    return pages;
  }

  for (const [sortKey, pagesByNumber] of Object.entries(rawPages)) {
    if (!pagesByNumber || typeof pagesByNumber !== 'object') {
      continue;
    }

    const normalizedPagesByNumber = {};
    for (const [page, records] of Object.entries(pagesByNumber)) {
      const pageNumber = coerceInteger(page, 0, { min: 1 });
      if (!pageNumber || !Array.isArray(records)) {
        continue;
      }

      const normalizedRecords = normalizeCacheRecords(records);
      if (normalizedRecords.length) {
        normalizedPagesByNumber[String(pageNumber)] = normalizedRecords;
      }
    }

    if (Object.keys(normalizedPagesByNumber).length) {
      pages[sortKey] = normalizedPagesByNumber;
    }
  }

  return pages;
}

async function readCatalogCache(
  storage,
  categoryId,
  {
    keyPrefix = CACHE_KEY_PREFIX,
    allowLegacy = false,
    ioTimeoutMs = CACHE_IO_TIMEOUT_MS,
  } = {},
) {
  if (!storage?.get) {
    return null;
  }

  try {
    const rawValue = await withTimeout(
      () => storage.get(getCatalogCacheKey(categoryId, keyPrefix)),
      ioTimeoutMs,
      `Widget.storage.get ${categoryId}`,
    );
    if (!rawValue) {
      return null;
    }

    return normalizeCache(JSON.parse(rawValue), categoryId, { allowLegacy });
  } catch {
    return null;
  }
}

async function readLegacyCatalogCache(storage, categoryId, { ioTimeoutMs = CACHE_IO_TIMEOUT_MS } = {}) {
  const caches = await Promise.all(
    LEGACY_CACHE_KEY_PREFIXES.map((keyPrefix) => readCatalogCache(storage, categoryId, {
      keyPrefix,
      allowLegacy: true,
      ioTimeoutMs,
    })),
  );

  for (const cache of caches) {
    if (cache?.records.length || Object.keys(cache?.pages ?? {}).length) {
      return cache;
    }
  }

  return null;
}

async function writeCatalogCache(storage, cache, { ioTimeoutMs = CACHE_IO_TIMEOUT_MS } = {}) {
  if (!storage?.set || !cache) {
    return;
  }

  try {
    await withTimeout(
      () => storage.set(getCatalogCacheKey(cache.categoryId), JSON.stringify(cache)),
      ioTimeoutMs,
      `Widget.storage.set ${cache.categoryId}`,
    );
  } catch {
    // 缓存只是加速与兜底层，写入失败不能影响当前页面展示。
  }
}

function mergeCachedRecords(existingRecords = [], incomingRecords = []) {
  const mergedByKey = new Map();

  for (const rawRecord of existingRecords) {
    const record = normalizeCacheRecord(rawRecord);
    if (record) {
      mergedByKey.set(`${record.mediaType}:${record.tmdbId}`, record);
    }
  }

  for (const rawRecord of incomingRecords) {
    const record = normalizeCacheRecord(rawRecord);
    if (record) {
      mergedByKey.set(`${record.mediaType}:${record.tmdbId}`, record);
    }
  }

  return sortCatalogRecords([...mergedByKey.values()], SORT_KEYS.DATE_DESC).slice(0, CACHE_MAX_RECORDS);
}

function getDateMs(dateText) {
  const timestamp = Date.parse(dateText || '');
  return Number.isNaN(timestamp) ? NaN : timestamp;
}

function getDaysBetween(leftDate, rightDate) {
  const leftMs = getDateMs(leftDate);
  const rightMs = getDateMs(rightDate);

  if (!Number.isFinite(leftMs) || !Number.isFinite(rightMs)) {
    return Number.POSITIVE_INFINITY;
  }

  return Math.max(0, Math.floor((rightMs - leftMs) / 86400000));
}

function shiftDate(dateText, offsetDays) {
  const timestamp = getDateMs(dateText);
  if (!Number.isFinite(timestamp)) {
    return '';
  }

  const date = new Date(timestamp);
  date.setUTCDate(date.getUTCDate() + offsetDays);
  return date.toISOString().slice(0, 10);
}

function withTimeout(taskFactory, timeoutMs, label) {
  if (typeof setTimeout !== 'function' || typeof clearTimeout !== 'function') {
    return taskFactory();
  }

  return new Promise((resolve, reject) => {
    const timer = setTimeout(() => {
      reject(new Error(`${label} timeout after ${timeoutMs}ms`));
    }, timeoutMs);

    Promise.resolve()
      .then(taskFactory)
      .then(resolve, reject)
      .finally(() => clearTimeout(timer));
  });
}

function createTimeoutTmdbGet(tmdbGet, timeoutMs = TMDB_REQUEST_TIMEOUT_MS) {
  return (pathName, options = {}) => {
    if (typeof setTimeout !== 'function' || typeof clearTimeout !== 'function') {
      return tmdbGet(pathName, options);
    }

    return new Promise((resolve, reject) => {
      const timer = setTimeout(() => {
        reject(new Error(`TMDb request timeout after ${timeoutMs}ms: ${pathName}`));
      }, timeoutMs);

      Promise.resolve()
        .then(() => tmdbGet(pathName, options))
        .then(resolve, reject)
        .finally(() => clearTimeout(timer));
    });
  };
}

function filterRecordsForResponse(records, params, todayDate) {
  return records.filter((record) =>
    hasRenderablePoster(record) &&
    isAllowedRecord(record, todayDate, params.categoryId, params.sortKey));
}

function paginateCacheRecords(records, params, todayDate) {
  const filteredRecords = filterRecordsForResponse(records, params, todayDate);
  const sortedRecords = sortCatalogRecords(filteredRecords, params.sortKey);
  const startIndex = (params.page - 1) * params.count;
  return sortedRecords.slice(startIndex, startIndex + params.count);
}

function getCachePageLimit(params) {
  // Forward 的分类入口预览可能用 count=1 请求同一个 page=1。
  // 页缓存没有单独按 count 分桶，所以写缓存时至少保留默认一页，
  // 避免一次预览请求把真正海报墙第一页污染成只有 1 张。
  return Math.max(params.count, DEFAULT_COUNT);
}

function sliceCurrentWindowRecords(records, params) {
  return sortCatalogRecords(records, params.sortKey).slice(0, getCachePageLimit(params));
}

async function fetchCurrentWindowRecords({ params, tmdbGet, todayDate }) {
  const {
    records,
    attemptedPages,
    failedPages,
    errors,
  } = await collectCatalogRecords({
    params,
    tmdbGet,
    todayDate,
    fetchPlan: getRemotePaginationPlan(params),
  });
  const sortedRecords = sortCatalogRecords(records, params.sortKey);

  return {
    records,
    responseRecords: sortedRecords.slice(0, params.count),
    cachePageRecords: sliceCurrentWindowRecords(records, params),
    attemptedPages,
    failedPages,
    errors,
  };
}

function mapRecordsToVideoItems(records, categoryTitle) {
  const seenItemIds = new Set();

  return records
    .filter(hasRenderablePoster)
    .map((record) => mapRecordToVideoItem(record, categoryTitle))
    .filter((item) => {
      if (seenItemIds.has(item.id)) {
        return false;
      }

      seenItemIds.add(item.id);
      return true;
    });
}

function getCategoryTitle(categoryId) {
  const mediaType = getCategoryMediaTypes(categoryId)[0] ?? MEDIA_TYPES.MOVIE;
  return getRuleById(mediaType, categoryId)?.title ?? categoryId;
}

function getCachedPageRecords(cache, sortKey, page) {
  const records = cache?.pages?.[sortKey]?.[String(page)];
  return normalizeCacheRecords(records);
}

function isFirstDateDescPage(params) {
  return params.sortKey === SORT_KEYS.DATE_DESC && params.page === 1;
}

function isPreviewPageRequest(params) {
  return params.page === 1 && params.count === 1;
}

function isCacheSyncedToday(cache, todayDate) {
  return normalizeTitle(cache?.lastSyncDate) === todayDate;
}

function getFirstRecordDateMs(records) {
  return getDateMs(records?.[0]?.releaseDate);
}

function isDateOlderThan(dateText, todayDate, maxAgeDays) {
  const dateMs = getDateMs(dateText);
  const todayMs = getDateMs(todayDate);
  if (!Number.isFinite(dateMs) || !Number.isFinite(todayMs)) {
    return false;
  }

  return todayMs - dateMs > maxAgeDays * 86400000;
}

function isCachedFirstPageTooOld(records, todayDate) {
  return isDateOlderThan(records?.[0]?.releaseDate, todayDate, FIRST_PAGE_STALE_MAX_AGE_DAYS);
}

function shouldRefreshCachedFirstPage(cache, cachedRecords, params, todayDate) {
  return (
    cachedRecords.length > 0 &&
    isFirstDateDescPage(params) &&
    (!isCacheSyncedToday(cache, todayDate) || isCachedFirstPageTooOld(cachedRecords, todayDate))
  );
}

function isRecordPoolNewerThanCachedPage(recordPoolPage, cachedPageRecords) {
  if (!recordPoolPage.length || !cachedPageRecords.length) {
    return false;
  }

  const recordPoolDateMs = getFirstRecordDateMs(recordPoolPage);
  const cachedPageDateMs = getFirstRecordDateMs(cachedPageRecords);

  return (
    Number.isFinite(recordPoolDateMs) &&
    (!Number.isFinite(cachedPageDateMs) || recordPoolDateMs > cachedPageDateMs)
  );
}

function getCachedResponseRecords(cache, params, todayDate) {
  const cachedPageRecords = sortCatalogRecords(
    filterRecordsForResponse(getCachedPageRecords(cache, params.sortKey, params.page), params, todayDate),
    params.sortKey,
  ).slice(0, params.count);
  const recordPoolPage = paginateCacheRecords(cache?.records ?? [], params, todayDate);

  if (isFirstDateDescPage(params) && isRecordPoolNewerThanCachedPage(recordPoolPage, cachedPageRecords)) {
    return {
      records: recordPoolPage,
      shouldRepairPageCache: true,
    };
  }

  if (cachedPageRecords.length) {
    return {
      records: cachedPageRecords,
      shouldRepairPageCache: false,
    };
  }

  if ((isPreviewPageRequest(params) || canUseCachedRecordPool(cache, params)) && recordPoolPage.length) {
    return {
      records: recordPoolPage,
      shouldRepairPageCache: false,
    };
  }

  return {
    records: [],
    shouldRepairPageCache: false,
  };
}

function getSequentialCachedPageCount(cache, sortKey) {
  const pagesByNumber = cache?.pages?.[sortKey];
  if (!pagesByNumber || typeof pagesByNumber !== 'object') {
    return 0;
  }

  let page = 1;
  while (normalizeCacheRecords(pagesByNumber[String(page)]).length) {
    page += 1;
  }

  return page - 1;
}

function canUseCachedRecordPool(cache, params) {
  if (!cache?.records?.length) {
    return false;
  }

  const requiredRecords = params.page * params.count;
  if (cache.records.length < requiredRecords) {
    return false;
  }

  return Math.max(
    getSequentialCachedPageCount(cache, params.sortKey),
    getSequentialCachedPageCount(cache, SORT_KEYS.DATE_DESC),
  ) >= params.page;
}

function setCachedPageRecords(cache, sortKey, page, records) {
  return {
    ...(cache?.pages ?? {}),
    [sortKey]: {
      ...(cache?.pages?.[sortKey] ?? {}),
      [String(page)]: normalizeCacheRecords(records),
    },
  };
}

function getCachedFallbackRecords(cache, params, todayDate) {
  const recordPoolPage = paginateCacheRecords(cache?.records ?? [], params, todayDate);
  if (recordPoolPage.length) {
    return recordPoolPage;
  }

  return [];
}

function didAllRemotePagesFail(fetchResult) {
  return fetchResult.attemptedPages > 0 && fetchResult.failedPages === fetchResult.attemptedPages;
}

function buildRemoteFailureError(params, categoryTitle, fetchResult) {
  const sample = fetchResult.errors
    .slice(0, 3)
    .map((error) => `${error.endpoint} ${error.language} p${error.page}: ${error.reason}`)
    .join('；');
  const details = sample ? `。示例：${sample}` : '';

  return new Error(`TMDb 分类加载失败：${categoryTitle} 第 ${params.page} 页远端请求全部失败${details}`);
}

function startBackgroundRefresh(task, overrides) {
  const safeTask = task.catch(() => {});
  if (Array.isArray(overrides.backgroundTasks)) {
    overrides.backgroundTasks.push(safeTask);
  }
}

function createOptionalTimeoutTmdbGet(overrides, timeoutMs = overrides.tmdbTimeoutMs ?? TMDB_REQUEST_TIMEOUT_MS) {
  try {
    return createTimeoutTmdbGet(
      overrides.tmdbGet ?? getDefaultTmdbGet(),
      timeoutMs,
    );
  } catch {
    return null;
  }
}

function getCacheRefreshTimeoutMs(overrides) {
  return overrides.cacheRefreshTimeoutMs ?? Math.min(
    overrides.tmdbTimeoutMs ?? CACHE_REFRESH_TIMEOUT_MS,
    CACHE_REFRESH_TIMEOUT_MS,
  );
}

function withDateDescFirstPageFromRecords(cache, params, todayDate, records) {
  const pageRecords = paginateCacheRecords(
    records,
    {
      ...params,
      sortKey: SORT_KEYS.DATE_DESC,
      page: 1,
      count: getCachePageLimit(params),
    },
    todayDate,
  );

  if (!pageRecords.length) {
    return cache;
  }

  return {
    ...cache,
    pages: setCachedPageRecords(cache, SORT_KEYS.DATE_DESC, 1, pageRecords),
  };
}

async function repairCachedPageFromRecords({ storage, cache, params, records }) {
  if (!storage || !cache || !records.length) {
    return;
  }

  await writeCatalogCache(storage, {
    ...cache,
    pages: setCachedPageRecords(cache, params.sortKey, params.page, records),
  });
}

async function fetchAndCacheCurrentWindow({ params, tmdbGet, storage, cache, todayDate }) {
  const fetchResult = await fetchCurrentWindowRecords({
    params,
    tmdbGet,
    todayDate,
  });
  const { records, responseRecords, cachePageRecords } = fetchResult;

  if (!records.length) {
    return responseRecords;
  }

  const baseCache = cache ?? createEmptyCache(params.categoryId, todayDate);
  const mergedRecords = mergeCachedRecords(baseCache.records ?? [], records);
  const responsePageRecords = isFirstDateDescPage(params)
    ? paginateCacheRecords(mergedRecords, params, todayDate)
    : responseRecords;
  const pageRecords = isFirstDateDescPage(params)
    ? paginateCacheRecords(
      mergedRecords,
      {
        ...params,
        count: getCachePageLimit(params),
      },
      todayDate,
    )
    : cachePageRecords;

  if (storage && pageRecords.length) {
    await writeCatalogCache(storage, {
      ...baseCache,
      lastSyncDate: todayDate,
      pages: setCachedPageRecords(baseCache, params.sortKey, params.page, pageRecords),
      records: mergedRecords,
    });
  }

  return responsePageRecords;
}

async function prefetchCatalogPage({ params, tmdbGet, storage, todayDate }) {
  if (!storage || !tmdbGet) {
    return;
  }

  const cachedCatalog = await readCatalogCache(storage, params.categoryId);
  if (getCachedPageRecords(cachedCatalog, params.sortKey, params.page).length) {
    return;
  }

  const { records, cachePageRecords } = await fetchCurrentWindowRecords({
    params,
    tmdbGet,
    todayDate,
  });

  if (!cachePageRecords.length) {
    return;
  }

  await writeCatalogCache(storage, {
    ...(cachedCatalog ?? createEmptyCache(params.categoryId, todayDate)),
    lastSyncDate: todayDate,
    pages: setCachedPageRecords(cachedCatalog, params.sortKey, params.page, cachePageRecords),
    records: mergeCachedRecords(cachedCatalog?.records ?? [], records),
  });
}

function startNextPagePrefetch({ params, tmdbGet, storage, todayDate, overrides }) {
  if (overrides.disableBackgroundPrefetch) {
    return;
  }

  for (let offset = 1; offset <= BACKGROUND_PREFETCH_PAGES; offset += 1) {
    startBackgroundRefresh(
      prefetchCatalogPage({
        params: {
          ...params,
          page: params.page + offset,
        },
        tmdbGet,
        storage,
        todayDate,
      }),
      overrides,
    );
  }
}

async function refreshCatalogCache({ params, tmdbGet, storage, cache, todayDate }) {
  let nextCache = cache ?? createEmptyCache(params.categoryId, todayDate);
  let nextRecords = nextCache.records;
  const daysSinceSync = getDaysBetween(nextCache.lastSyncDate, todayDate);
  const daysSinceBackfill = getDaysBetween(nextCache.lastBackfillDate || nextCache.lastSyncDate, todayDate);

  if (daysSinceSync <= 0) {
    return;
  }

  if (daysSinceSync > 0) {
    const incrementalFetchPlan = {
      sourceStartPage: 1,
      requestedSourcePages: INCREMENTAL_REFRESH_MAX_SOURCE_PAGES,
    };
    const shouldUseDateIncrement = daysSinceSync <= INCREMENTAL_REFRESH_MAX_DAYS;
    const dateRange = shouldUseDateIncrement
      ? {
          from: nextCache.lastSyncDate,
          to: todayDate,
        }
      : null;
    const refreshFetchPlan = shouldUseDateIncrement ? incrementalFetchPlan : getRemotePaginationPlan(params);
    const { records } = await collectCatalogRecords({
      params,
      tmdbGet,
      todayDate,
      fetchPlan: refreshFetchPlan,
      sortKey: SORT_KEYS.DATE_DESC,
      dateRange,
    });

    nextRecords = mergeCachedRecords(nextRecords, records);
    nextCache = {
      ...nextCache,
      lastSyncDate: todayDate,
      records: nextRecords,
    };
    nextCache = withDateDescFirstPageFromRecords(nextCache, params, todayDate, nextRecords);
  }

  if (daysSinceBackfill >= BACKFILL_INTERVAL_DAYS) {
    const { records } = await collectCatalogRecords({
      params,
      tmdbGet,
      todayDate,
      fetchPlan: {
        sourceStartPage: 1,
        requestedSourcePages: INCREMENTAL_REFRESH_MAX_SOURCE_PAGES,
      },
      sortKey: SORT_KEYS.DATE_DESC,
      dateRange: {
        from: shiftDate(todayDate, -BACKFILL_LOOKBACK_DAYS),
        to: todayDate,
      },
    });

    nextRecords = mergeCachedRecords(nextRecords, records);
    nextCache = {
      ...nextCache,
      lastBackfillDate: todayDate,
      records: nextRecords,
    };
    nextCache = withDateDescFirstPageFromRecords(nextCache, params, todayDate, nextRecords);
  }

  await writeCatalogCache(storage, nextCache);
}

function getLegacyCategoryValue(params = {}) {
  const legacyMediaType = params.mediaType === MEDIA_TYPES.TV ? MEDIA_TYPES.TV : MEDIA_TYPES.MOVIE;
  return legacyMediaType === MEDIA_TYPES.TV ? params.tvCategory : params.movieCategory;
}

function normalizeBrowseParams(params = {}) {
  const sortValue = params.sort_by ?? params.movieSort ?? params.tvSort;
  const categoryId = pickValidValue(
    params.category ?? getLegacyCategoryValue(params),
    getCategoryOptions(),
    getDefaultCategory(),
  );
  const sortKey = pickValidValue(sortValue, getSortOptions(), getDefaultSort());
  const count = coerceInteger(params.count, DEFAULT_COUNT, { min: 1, max: MAX_COUNT });
  const page = coerceInteger(params.page, DEFAULT_PAGE, { min: 1 });

  return {
    categoryId,
    sortKey,
    count,
    page,
  };
}

async function browseCatalog(rawParams = {}, overrides = {}) {
  const params = normalizeBrowseParams(rawParams);
  const storage = overrides.storage ?? getDefaultStorage();
  const todayDate = overrides.todayDate ?? getTodayDateString();
  const categoryTitle = getCategoryTitle(params.categoryId);
  const cacheIoTimeoutMs = overrides.cacheIoTimeoutMs ?? CACHE_IO_TIMEOUT_MS;
  const cachedCatalog = await readCatalogCache(storage, params.categoryId, { ioTimeoutMs: cacheIoTimeoutMs });
  const cachedResponse = getCachedResponseRecords(cachedCatalog, params, todayDate);

  if (shouldRefreshCachedFirstPage(cachedCatalog, cachedResponse.records, params, todayDate)) {
    const refreshTimeoutMs = isCachedFirstPageTooOld(cachedResponse.records, todayDate)
      ? (overrides.tmdbTimeoutMs ?? TMDB_REQUEST_TIMEOUT_MS)
      : getCacheRefreshTimeoutMs(overrides);
    const tmdbGet = createOptionalTimeoutTmdbGet(overrides, refreshTimeoutMs);
    if (tmdbGet) {
      try {
        const freshRecords = await fetchAndCacheCurrentWindow({
          params,
          tmdbGet,
          storage,
          cache: cachedCatalog,
          todayDate,
        });

        if (freshRecords.length) {
          return mapRecordsToVideoItems(freshRecords, categoryTitle);
        }
      } catch {
        // 首页新鲜度刷新是“尽力而为”：失败时继续返回已有缓存，避免刷新后白屏。
      }
    }
  }

  if (cachedResponse.records.length) {
    if (cachedResponse.shouldRepairPageCache) {
      await repairCachedPageFromRecords({
        storage,
        cache: cachedCatalog,
        params,
        records: cachedResponse.records,
      });
    }

    const tmdbGet = createOptionalTimeoutTmdbGet(overrides);
    if (!overrides.disableBackgroundRefresh) {
      if (tmdbGet) {
        startBackgroundRefresh(
          refreshCatalogCache({
            params,
            tmdbGet,
            storage,
            cache: cachedCatalog,
            todayDate,
          }),
          overrides,
        );
      }
    }
    startNextPagePrefetch({ params, tmdbGet, storage, todayDate, overrides });

    return mapRecordsToVideoItems(cachedResponse.records, categoryTitle);
  }

  if (isPreviewPageRequest(params)) {
    const legacyCachedCatalog = await readLegacyCatalogCache(storage, params.categoryId, { ioTimeoutMs: cacheIoTimeoutMs });
    const legacyFallbackRecords = getCachedFallbackRecords(legacyCachedCatalog, params, todayDate);
    if (legacyFallbackRecords.length) {
      const tmdbGet = createOptionalTimeoutTmdbGet(overrides);
      if (tmdbGet) {
        startBackgroundRefresh(
          fetchAndCacheCurrentWindow({
            params,
            tmdbGet,
            storage,
            cache: null,
            todayDate,
          }),
          overrides,
        );
      }

      return mapRecordsToVideoItems(legacyFallbackRecords, categoryTitle);
    }
  }

  const tmdbGet = createTimeoutTmdbGet(
    overrides.tmdbGet ?? getDefaultTmdbGet(),
    overrides.tmdbTimeoutMs ?? TMDB_REQUEST_TIMEOUT_MS,
  );
  const fetchResult = await fetchCurrentWindowRecords({
    params,
    tmdbGet,
    todayDate,
  });
  const { records, responseRecords, cachePageRecords } = fetchResult;

  if (!responseRecords.length) {
    let fallbackRecords = getCachedFallbackRecords(cachedCatalog, params, todayDate);
    if (!fallbackRecords.length) {
      const legacyCachedCatalog = await readLegacyCatalogCache(storage, params.categoryId, { ioTimeoutMs: cacheIoTimeoutMs });
      fallbackRecords = getCachedFallbackRecords(legacyCachedCatalog, params, todayDate);
    }

    if (fallbackRecords.length) {
      return mapRecordsToVideoItems(fallbackRecords, categoryTitle);
    }

    if (didAllRemotePagesFail(fetchResult)) {
      throw buildRemoteFailureError(params, categoryTitle, fetchResult);
    }
  }

  if (storage && records.length) {
    const mergedRecords = mergeCachedRecords(cachedCatalog?.records ?? [], records);
    await writeCatalogCache(storage, {
      ...(cachedCatalog ?? createEmptyCache(params.categoryId, todayDate)),
      lastSyncDate: todayDate,
      pages: setCachedPageRecords(cachedCatalog, params.sortKey, params.page, cachePageRecords),
      records: mergedRecords,
    }, { ioTimeoutMs: cacheIoTimeoutMs });
  }

  return mapRecordsToVideoItems(responseRecords, categoryTitle);
}

const MP_DEFAULT_BASE_URL = 'http://192.168.31.2:3001';
const MP_REQUEST_TIMEOUT_MS = 8000;

const MP_MEDIA_TYPE_OPTIONS = Object.freeze([
  { title: '全部', value: 'all' },
  { title: '电影', value: MEDIA_TYPES.MOVIE },
  { title: '剧集', value: MEDIA_TYPES.TV },
]);

const MP_SORT_OPTIONS = Object.freeze([
  { title: '最近订阅', value: 'date_desc' },
  { title: '最近更新', value: 'updated_desc' },
  { title: '标题', value: 'title_asc' },
]);

function mpNormalizeText(value) {
  return typeof value === 'string' ? value.trim() : '';
}

function mpCoerceInteger(value, fallback, { min = 1, max = Number.MAX_SAFE_INTEGER } = {}) {
  const parsed = Number.parseInt(String(value ?? ''), 10);

  if (!Number.isFinite(parsed)) {
    return fallback;
  }

  return Math.min(Math.max(parsed, min), max);
}

function mpPickValue(value, options, fallback) {
  const validValues = new Set(options.map((option) => option.value));
  return validValues.has(value) ? value : fallback;
}

function mpNormalizeBaseUrl(value) {
  const normalized = mpNormalizeText(value) || MP_DEFAULT_BASE_URL;
  return normalized.replace(/\/+$/, '');
}

function mpNormalizeImageUrl(path) {
  const normalizedPath = mpNormalizeText(path);
  if (!normalizedPath) {
    return '';
  }

  if (/^https?:\/\//i.test(normalizedPath)) {
    return normalizedPath;
  }

  return normalizedPath.startsWith('/') ? `${TMDB_IMAGE_BASE}/w500${normalizedPath}` : normalizedPath;
}

function mpNormalizeBackdropUrl(path) {
  const normalizedPath = mpNormalizeText(path);
  if (!normalizedPath) {
    return '';
  }

  if (/^https?:\/\//i.test(normalizedPath)) {
    return normalizedPath;
  }

  return normalizedPath.startsWith('/') ? `${TMDB_IMAGE_BASE}/w780${normalizedPath}` : normalizedPath;
}

function mpNormalizeMediaType(value) {
  const normalized = mpNormalizeText(value).toLowerCase();

  if (normalized === MEDIA_TYPES.MOVIE || normalized === '电影' || normalized === 'movie') {
    return MEDIA_TYPES.MOVIE;
  }

  if (
    normalized === MEDIA_TYPES.TV ||
    normalized === '电视剧' ||
    normalized === '剧集' ||
    normalized === 'tv' ||
    normalized === 'series'
  ) {
    return MEDIA_TYPES.TV;
  }

  return '';
}

function mpParseTmdbId(rawSubscribe) {
  const directTmdbId = mpCoerceInteger(rawSubscribe?.tmdbid ?? rawSubscribe?.tmdb_id, 0, { min: 0 });
  if (directTmdbId) {
    return directTmdbId;
  }

  const mediaId = mpNormalizeText(rawSubscribe?.mediaid ?? rawSubscribe?.media_id);
  const matched = mediaId.match(/(?:tmdb|movie|tv)[:.](\d+)/i);
  return matched ? mpCoerceInteger(matched[1], 0, { min: 0 }) : 0;
}

function mpGetDefaultHttpGet() {
  if (typeof Widget === 'undefined' || !Widget?.http?.get) {
    throw new Error('当前运行环境缺少 Widget.http.get，无法请求 MoviePilot。');
  }

  return Widget.http.get.bind(Widget.http);
}

function mpWithTimeout(taskFactory, timeoutMs, label) {
  if (typeof setTimeout !== 'function' || typeof clearTimeout !== 'function') {
    return taskFactory();
  }

  return new Promise((resolve, reject) => {
    const timer = setTimeout(() => {
      reject(new Error(`${label} timeout after ${timeoutMs}ms`));
    }, timeoutMs);

    Promise.resolve()
      .then(taskFactory)
      .then(resolve, reject)
      .finally(() => clearTimeout(timer));
  });
}

function normalizeMoviePilotParams(params = {}) {
  return {
    baseUrl: mpNormalizeBaseUrl(params.mp_base_url),
    apiToken: mpNormalizeText(params.api_token),
    mediaType: mpPickValue(params.media_type, MP_MEDIA_TYPE_OPTIONS, 'all'),
    sortKey: mpPickValue(params.sort_by, MP_SORT_OPTIONS, 'date_desc'),
    count: mpCoerceInteger(params.count, DEFAULT_COUNT, { min: 1, max: MAX_COUNT }),
    page: mpCoerceInteger(params.page, DEFAULT_PAGE, { min: 1 }),
  };
}

function normalizeMoviePilotSubscribe(rawSubscribe) {
  const tmdbId = mpParseTmdbId(rawSubscribe);
  const mediaType = mpNormalizeMediaType(rawSubscribe?.type);

  if (!tmdbId || !mediaType) {
    return null;
  }

  const title = mpNormalizeText(rawSubscribe?.name || rawSubscribe?.title || rawSubscribe?.keyword);
  if (!title) {
    return null;
  }

  return {
    id: mpCoerceInteger(rawSubscribe?.id, tmdbId, { min: 1 }),
    tmdbId,
    mediaType,
    title,
    year: mpNormalizeText(rawSubscribe?.year),
    season: mpCoerceInteger(rawSubscribe?.season, 0, { min: 0 }),
    posterPath: mpNormalizeImageUrl(rawSubscribe?.poster),
    backdropPath: mpNormalizeBackdropUrl(rawSubscribe?.backdrop),
    description: mpNormalizeText(rawSubscribe?.description),
    rating: Number.isFinite(rawSubscribe?.vote) ? rawSubscribe.vote : 0,
    date: mpNormalizeText(rawSubscribe?.date),
    lastUpdate: mpNormalizeText(rawSubscribe?.last_update),
    totalEpisode: mpCoerceInteger(rawSubscribe?.total_episode, 0, { min: 0 }),
    lackEpisode: mpCoerceInteger(rawSubscribe?.lack_episode, 0, { min: 0 }),
    state: mpNormalizeText(rawSubscribe?.state),
    mediaCategory: mpNormalizeText(rawSubscribe?.media_category),
  };
}

function sortMoviePilotSubscribes(records, sortKey) {
  const sorted = [...records];

  sorted.sort((left, right) => {
    switch (sortKey) {
      case 'updated_desc':
        return (
          right.lastUpdate.localeCompare(left.lastUpdate) ||
          right.date.localeCompare(left.date) ||
          left.title.localeCompare(right.title, 'zh-Hans-CN')
        );
      case 'title_asc':
        return left.title.localeCompare(right.title, 'zh-Hans-CN') || right.date.localeCompare(left.date);
      case 'date_desc':
      default:
        return (
          right.date.localeCompare(left.date) ||
          right.lastUpdate.localeCompare(left.lastUpdate) ||
          left.title.localeCompare(right.title, 'zh-Hans-CN')
        );
    }
  });

  return sorted;
}

function buildMoviePilotDescription(record) {
  const meta = [
    record.year,
    record.mediaType === MEDIA_TYPES.TV && record.season ? `第 ${record.season} 季` : '',
    record.totalEpisode ? `${record.totalEpisode} 集` : '',
    record.lackEpisode ? `缺 ${record.lackEpisode} 集` : '',
    record.state,
  ].filter(Boolean);
  const body = record.description || 'MoviePilot 订阅';

  return [meta.join(' · '), body].filter(Boolean).join('\n');
}

function mapMoviePilotSubscribeToVideoItem(record) {
  return {
    id: String(record.tmdbId),
    tmdbId: record.tmdbId,
    type: 'tmdb',
    title: record.year ? `${record.title} (${record.year})` : record.title,
    subTitle: '',
    posterPath: record.posterPath,
    backdropPath: record.backdropPath,
    releaseDate: record.date || record.lastUpdate || undefined,
    mediaType: record.mediaType,
    genreTitle: record.mediaCategory || (record.mediaType === MEDIA_TYPES.TV ? 'MP 订阅剧集' : 'MP 订阅电影'),
    description: buildMoviePilotDescription(record),
    rating: record.rating,
  };
}

async function fetchMoviePilotSubscribes(params, httpGet) {
  if (!params.apiToken) {
    throw new Error('缺少 MoviePilot API_TOKEN，请在模块参数 api_token 中填写。');
  }

  const response = await mpWithTimeout(
    () => httpGet(`${params.baseUrl}/api/v1/subscribe/list`, {
      params: {
        token: params.apiToken,
      },
    }),
    MP_REQUEST_TIMEOUT_MS,
    'MoviePilot subscribe/list',
  );

  if (response.statusCode < 200 || response.statusCode >= 300) {
    throw new Error(`MoviePilot 订阅接口返回 HTTP ${response.statusCode}`);
  }

  if (!Array.isArray(response.data)) {
    throw new Error('MoviePilot 订阅接口返回格式不是数组。');
  }

  return response.data;
}

async function browseMoviePilotSubscriptions(rawParams = {}, overrides = {}) {
  const params = normalizeMoviePilotParams(rawParams);
  const httpGet = overrides.httpGet ?? mpGetDefaultHttpGet();
  const rawSubscribes = await fetchMoviePilotSubscribes(params, httpGet);
  const records = rawSubscribes
    .map((item) => normalizeMoviePilotSubscribe(item))
    .filter(Boolean)
    .filter((item) => params.mediaType === 'all' || item.mediaType === params.mediaType);
  const sortedRecords = sortMoviePilotSubscribes(records, params.sortKey);
  const startIndex = (params.page - 1) * params.count;

  return sortedRecords
    .slice(startIndex, startIndex + params.count)
    .map((record) => mapMoviePilotSubscribeToVideoItem(record));
}

var WidgetMetadata = {
  id: 'tmdb-category-browser',
  title: 'TMDb 剧集/电影分类',
  description: '纯 TMDb 直连分类墙，只保留 TMDb 分类列表、双语混抓、过滤、排序与分页。',
  version: "0.6.21",
  requiredVersion: '0.0.1',
  author: 'Codex',
  modules: [
    {
      id: 'tmdb-category-browser',
      title: '影视分类',
      description: '纯 TMDb 分类墙，不含翻译代理、目录代理与自定义详情链路。',
      functionName: 'browseTmdbCategories',
      type: 'video',
      cacheDuration: 1,
      params: [
        {
          name: 'cache_rev',
          title: '缓存版本',
          description: '内部缓存刷新标记，用于让 Forward 客户端丢弃旧模块结果缓存。',
          type: 'constant',
          value: 'v0.6.21',
        },
        {
          name: 'sort_by',
          title: '排序方式',
          type: 'enumeration',
          value: 'date_desc',
          enumOptions: SORT_OPTIONS,
        },
        {
          name: 'category',
          title: '分类',
          type: 'enumeration',
          value: 'chinese_movie',
          enumOptions: CATEGORY_OPTIONS,
        },
        {
          name: 'count',
          title: '每页数量',
          type: 'count',
          value: '20',
          placeholders: [
            {
              title: '10 条',
              value: '10',
            },
            {
              title: '20 条',
              value: '20',
            },
            {
              title: '40 条',
              value: '40',
            },
            {
              title: '60 条',
              value: '60',
            },
          ],
        },
        {
          name: 'page',
          title: '页码',
          type: 'page',
          value: '1',
        },
      ],
    },
    {
      id: 'moviepilot-subscriptions',
      title: 'MoviePilot 订阅',
      description: '读取本机 MoviePilot 的订阅列表，订阅后在 Forward 中按原生 TMDb 卡片展示。',
      functionName: 'browseMoviePilotSubscriptions',
      type: 'video',
      cacheDuration: 60,
      params: [
        {
          name: 'mp_base_url',
          title: 'MP 地址',
          description: 'MoviePilot 后端地址。手机或平板访问时请填写 Mac 的局域网地址。',
          type: 'input',
          value: 'http://192.168.31.2:3001',
        },
        {
          name: 'api_token',
          title: 'API_TOKEN',
          description: 'MoviePilot API_TOKEN。只用于请求 /api/v1/subscribe/list。',
          type: 'input',
          value: '',
        },
        {
          name: 'media_type',
          title: '类型',
          type: 'enumeration',
          value: 'all',
          enumOptions: MP_MEDIA_TYPE_OPTIONS,
        },
        {
          name: 'sort_by',
          title: '排序方式',
          type: 'enumeration',
          value: 'date_desc',
          enumOptions: MP_SORT_OPTIONS,
        },
        {
          name: 'count',
          title: '每页数量',
          type: 'count',
          value: '20',
          placeholders: [
            {
              title: '10 条',
              value: '10',
            },
            {
              title: '20 条',
              value: '20',
            },
            {
              title: '40 条',
              value: '40',
            },
            {
              title: '60 条',
              value: '60',
            },
          ],
        },
        {
          name: 'page',
          title: '页码',
          type: 'page',
          value: '1',
        },
      ],
    },
  ],
};

// 视频卡片统一走 Forward 原生 TMDb 链路，不再经过 Worker 目录代理或自定义详情封装。
async function browseTmdbCategories(params) {
  return browseCatalog(params);
}
